<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <title>@yield('title', __('sms.home.title'))</title>
    <meta name="description" content="{{ __('sms.meta_description') }}">
    <style>
        :root{
            color-scheme:dark;
            --ink:#f8f7ff;--soft:#bfc3d6;--muted:#7f8499;--void:#050509;--obsidian:#090a10;
            --shell:rgba(255,255,255,.065);--core:#0d0e15;--core2:#151722;--hair:rgba(255,255,255,.115);
            --violet:#8b6cff;--violet2:#c1a9ff;--cyan:#73e7ff;--mint:#7af2be;--rose:#ff6d8b;--amber:#ffd27a;
            --max:1240px;--nav-max:1120px;--radius:32px;--radius-sm:22px;
            --spring:cubic-bezier(.32,.72,0,1);--heavy:cubic-bezier(.16,1,.3,1);
            --ambient:0 42px 140px rgba(0,0,0,.42),0 0 0 1px rgba(255,255,255,.025);
        }
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;min-height:100dvh;background:var(--void);color:var(--ink);font-family:"Geist","Plus Jakarta Sans",ui-sans-serif,system-ui,sans-serif;letter-spacing:-.015em;overflow-x:hidden}
        body:before{content:"";position:fixed;inset:0;z-index:-3;background:radial-gradient(circle at 13% 8%,rgba(139,108,255,.32),transparent 32%),radial-gradient(circle at 82% 5%,rgba(115,231,255,.16),transparent 28%),radial-gradient(circle at 54% 92%,rgba(122,242,190,.09),transparent 36%),linear-gradient(180deg,#050509 0%,#0a0b12 46%,#11121a 100%);pointer-events:none}
        body:after{content:"";position:fixed;inset:0;z-index:-2;pointer-events:none;opacity:.34;background-image:linear-gradient(rgba(255,255,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.027) 1px,transparent 1px);background-size:56px 56px;mask-image:linear-gradient(to bottom,rgba(0,0,0,.72),transparent 76%)}
        a{color:inherit;text-decoration:none}button,input,select,textarea{font:inherit}.container{width:min(var(--max),calc(100vw - 48px));margin-inline:auto}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace}.muted{color:var(--soft)}.dim{color:var(--muted)}
        .topbar{position:sticky;top:18px;z-index:30;width:min(var(--nav-max),calc(100vw - 28px));margin:18px auto 0;pointer-events:none}.topbar-inner{pointer-events:auto;min-height:76px;display:flex;align-items:center;justify-content:space-between;gap:18px;padding:10px 12px 10px 14px;border-radius:999px;background:rgba(8,9,15,.72);border:1px solid rgba(255,255,255,.12);box-shadow:0 22px 90px rgba(0,0,0,.32),inset 0 1px 0 rgba(255,255,255,.12);backdrop-filter:blur(26px)}
        .brand{display:flex;align-items:center;gap:12px;font-weight:950;letter-spacing:-.04em}.brand-mark{width:50px;height:50px;border-radius:18px;background:linear-gradient(135deg,#9376ff,#4d2ed6);display:grid;place-items:center;position:relative;overflow:hidden;box-shadow:0 18px 50px rgba(139,108,255,.36),inset 0 1px 1px rgba(255,255,255,.35)}.brand-mark:after{content:"";position:absolute;width:80px;height:22px;top:8px;left:-20px;transform:rotate(-27deg);background:rgba(255,255,255,.22)}.brand-mark span{position:relative;font-size:23px}.brand-name{font-size:24px;line-height:.96}.brand-name em{font-style:normal;color:var(--violet2)}.brand-domain{display:block;margin-top:4px;font-size:11px;letter-spacing:.08em;color:var(--muted);font-weight:800}
        .nav{display:flex;align-items:center;justify-content:center;gap:4px;flex:1}.nav a{padding:13px 15px;border-radius:999px;color:#e9e8f4;font-size:14px;font-weight:850;transition:transform .7s var(--spring),background .7s var(--spring),color .7s var(--spring)}.nav a:hover,.nav a.active{transform:translateY(-1px);background:rgba(255,255,255,.085);color:#fff}.userbar{display:flex;align-items:center;gap:10px}.lang-switch select{min-height:44px;border-radius:999px;padding:8px 34px 8px 14px;background-color:rgba(255,255,255,.07);font-size:13px;font-weight:850}.avatar{width:46px;height:46px;border-radius:999px;display:grid;place-items:center;background:linear-gradient(180deg,#f5f4ff,#d9d4ff);color:#6d4df5;font-weight:950}.user-meta{line-height:1.1;font-weight:900;font-size:13px}.user-meta small{display:block;color:var(--violet2);margin-top:4px}.menu-btn{display:none;position:relative;width:54px;height:54px;border-radius:999px;border:1px solid rgba(255,255,255,.11);background:rgba(255,255,255,.065);color:#fff;padding:0;box-shadow:none}.menu-btn span{position:absolute;left:16px;right:16px;height:1.5px;border-radius:99px;background:#fff;transition:transform .7s var(--spring),opacity .55s var(--spring)}.menu-btn span:nth-child(1){top:20px}.menu-btn span:nth-child(2){top:27px}.menu-btn span:nth-child(3){top:34px}.menu-btn.is-open span:nth-child(1){transform:translateY(7px) rotate(45deg)}.menu-btn.is-open span:nth-child(2){opacity:0;transform:scaleX(.25)}.menu-btn.is-open span:nth-child(3){transform:translateY(-7px) rotate(-45deg)}
        .mobile-menu.container{position:fixed;inset:0;z-index:25;width:auto;max-width:none;margin:0;padding:122px 24px 34px;display:grid;align-content:start;gap:10px;background:rgba(5,5,9,.86);backdrop-filter:blur(32px);opacity:0;pointer-events:none;transform:scale(.985);transition:opacity .7s var(--spring),transform .7s var(--spring)}.mobile-menu.open{opacity:1;pointer-events:auto;transform:scale(1)}.mobile-menu a,.mobile-menu button{width:100%;display:flex;justify-content:space-between;align-items:center;border:0;border-radius:26px;padding:18px 22px;background:rgba(255,255,255,.065);color:#fff;font-size:24px;font-weight:950;opacity:0;transform:translateY(36px);transition:opacity .7s var(--spring),transform .7s var(--spring),background .7s var(--spring)}.mobile-menu.open a,.mobile-menu.open button{opacity:1;transform:translateY(0)}.mobile-menu.open a:nth-child(2){transition-delay:.08s}.mobile-menu.open a:nth-child(3){transition-delay:.13s}.mobile-menu.open a:nth-child(4){transition-delay:.18s}.mobile-menu.open a:nth-child(5){transition-delay:.23s}.mobile-langs{display:flex!important;gap:10px;padding:0 0 10px!important}.mobile-langs a{justify-content:center;font-size:14px;border:1px solid rgba(255,255,255,.12);border-radius:999px;padding:12px 14px}
        .btn{display:inline-flex;align-items:center;justify-content:center;gap:10px;min-height:50px;border:0;border-radius:999px;padding:14px 22px;font-weight:950;cursor:pointer;text-decoration:none;transition:transform .7s var(--spring),background .7s var(--spring),opacity .7s var(--spring),box-shadow .7s var(--spring);will-change:transform}.btn:hover{transform:translateY(-2px)}.btn:active{transform:scale(.985)}.btn-primary{background:linear-gradient(135deg,var(--violet),var(--violet2));color:#fff;box-shadow:0 18px 54px rgba(139,108,255,.26),inset 0 1px 1px rgba(255,255,255,.32)}.btn-primary[href]:not(.btn-block):after,.hero-actions .btn-primary:after{content:"↗";width:28px;height:28px;border-radius:999px;background:rgba(255,255,255,.18);display:grid;place-items:center;margin-right:-8px;transition:transform .7s var(--spring),background .7s var(--spring)}.btn-primary[href]:not(.btn-block):hover:after,.hero-actions .btn-primary:hover:after{transform:translate(4px,-1px) scale(1.05)}.btn-white{background:#f7f5ff;color:#101018}.btn-dark,.btn-ghost{background:rgba(255,255,255,.07);color:#fff;border:1px solid rgba(255,255,255,.12);box-shadow:inset 0 1px 0 rgba(255,255,255,.08)}.btn-danger{background:rgba(255,109,139,.16);color:#ffdce5;border:1px solid rgba(255,109,139,.35)}.btn-block{width:100%}
        .section{padding:112px 0}.section-tight{padding:76px 0}.section-title{margin:0 0 20px;font-size:clamp(38px,5.1vw,74px);line-height:1.02;letter-spacing:-.065em;overflow-wrap:anywhere;word-break:break-word}.section-sub{color:var(--soft);font-size:clamp(16px,1.9vw,23px);line-height:1.68;max-width:900px;margin:0 auto 54px}.eyebrow{display:inline-flex;align-items:center;gap:8px;margin-bottom:22px;border:1px solid rgba(255,255,255,.11);background:rgba(255,255,255,.065);border-radius:999px;padding:8px 12px;color:#e6e0ff;font-size:10px;text-transform:uppercase;letter-spacing:.2em;font-weight:850}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:26px}.grid3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}.grid4{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:20px}.grid5{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:20px}
        .panel,.feature-card,.step-card,.faq-card,.pay-card,.stat{min-width:0;position:relative;border-radius:var(--radius);padding:7px;background:linear-gradient(180deg,rgba(255,255,255,.105),rgba(255,255,255,.035));border:1px solid rgba(255,255,255,.105);box-shadow:var(--ambient)}.panel:before,.feature-card:before,.step-card:before,.faq-card:before,.pay-card:before,.stat:before{content:"";position:absolute;inset:7px;border-radius:calc(var(--radius) - 7px);background:linear-gradient(180deg,rgba(20,21,32,.97),rgba(9,10,15,.985));box-shadow:inset 0 1px 1px rgba(255,255,255,.13),inset 0 -1px 0 rgba(255,255,255,.04);z-index:0}.panel>* ,.feature-card>* ,.step-card>* ,.faq-card>* ,.pay-card>* ,.stat>*{position:relative;z-index:1}.panel{padding:30px}.panel:before{inset:6px}.panel-black:before{background:linear-gradient(180deg,#0a0b10,#06070a)}.feature-card,.step-card,.stat{padding:32px}.feature-card h3,.step-card h3{font-size:25px;margin:18px 0 10px;letter-spacing:-.035em}.feature-card p,.step-card p{color:var(--soft);line-height:1.75;margin:0}.icon,.number-badge{width:46px;height:46px;border-radius:999px;display:grid;place-items:center;background:linear-gradient(135deg,#f4f2ff,#d7d0ff);color:#6d4df5;font-weight:950;box-shadow:inset 0 1px 1px rgba(255,255,255,.8)}
        label{display:block;margin:0 0 10px;color:#fbfaff;font-weight:900}.input,select,textarea,input[type="email"],input[type="password"],input[type="text"],input[type="number"]{width:100%;min-height:56px;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.065);color:var(--ink);border-radius:20px;padding:15px 16px;outline:none;transition:border-color .7s var(--spring),box-shadow .7s var(--spring),transform .7s var(--spring)}input::placeholder,textarea::placeholder{color:#767c93}.input:focus,select:focus,textarea:focus,input:focus{border-color:rgba(193,169,255,.8);box-shadow:0 0 0 5px rgba(139,108,255,.16);transform:translateY(-1px)}select{appearance:none;background-image:linear-gradient(45deg,transparent 50%,#d8ceff 50%),linear-gradient(135deg,#d8ceff 50%,transparent 50%);background-position:calc(100% - 22px) 24px,calc(100% - 14px) 24px;background-size:8px 8px;background-repeat:no-repeat}.field{margin-bottom:20px}.help{font-size:13px;color:var(--soft);line-height:1.7}.price{font-size:clamp(42px,5.8vw,78px);font-weight:1000;color:#fff;letter-spacing:-.06em}.pill,.status{display:inline-flex;align-items:center;gap:8px;border-radius:999px;padding:8px 12px;background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.12);color:#eeeaff;font-weight:900}.status{font-size:13px;color:#dfd6ff;background:rgba(139,108,255,.14)}
        .ok,.err{width:min(var(--max),calc(100vw - 48px));margin:20px auto 0;border-radius:22px;padding:16px 18px;font-weight:850;border:1px solid rgba(255,255,255,.11);box-shadow:var(--ambient)}.ok{background:rgba(122,242,190,.12);color:#ddfff1}.err{background:rgba(255,109,139,.13);color:#ffe0e7}.table-wrap{overflow:auto;border-radius:24px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08)}.table{width:100%;border-collapse:collapse;min-width:760px}.table th,.table td{border-bottom:1px solid rgba(255,255,255,.075);padding:17px 14px;text-align:left;vertical-align:top}.table th{color:#fff;font-size:12px;text-transform:uppercase;letter-spacing:.14em}.table td{color:#d9dced}.copy-row{display:grid;grid-template-columns:1fr auto;gap:12px}.copy-row .btn{border-radius:18px;min-width:118px}
        .footer{padding:64px 0;color:#8d94aa;margin-top:54px}.footer-inner{display:flex;justify-content:space-between;gap:24px;flex-wrap:wrap;border-top:1px solid rgba(255,255,255,.08);padding-top:26px}.footer a{color:#d4d7e6;margin-right:16px}.chat-float{position:fixed;right:28px;bottom:28px;z-index:20;width:58px;height:58px;border-radius:999px;display:grid;place-items:center;background:rgba(139,108,255,.16);border:1px solid rgba(193,169,255,.38);box-shadow:0 22px 70px rgba(0,0,0,.35);color:#f1ebff;font-size:22px}
        .carousel{position:relative;min-height:520px;overflow:hidden}.slide{position:absolute;inset:0;opacity:0;transform:translateX(26px) scale(.985);transition:opacity .9s var(--spring),transform .9s var(--spring)}.slide.active{opacity:1;transform:translateX(0) scale(1)}.dots{position:absolute;left:0;right:0;bottom:0;display:flex;justify-content:center;gap:8px}.dot{width:9px;height:9px;border:0;border-radius:999px;background:rgba(255,255,255,.32);padding:0;transition:width .75s var(--spring),background .75s var(--spring)}.dot.active{width:34px;background:#fff}.service-preview{display:flex;flex-direction:column;gap:14px}.service-item{position:relative;overflow:hidden;display:grid;grid-template-columns:auto 1fr auto;gap:16px;align-items:center;border-radius:28px;padding:7px;background:linear-gradient(180deg,rgba(255,255,255,.11),rgba(255,255,255,.035));border:1px solid rgba(255,255,255,.1);color:#fff;text-align:left;transition:transform .75s var(--spring),background .75s var(--spring),border-color .75s var(--spring)}.service-item:hover{transform:translateY(-3px)}.service-item.is-active{border-color:rgba(193,169,255,.58);background:linear-gradient(180deg,rgba(139,108,255,.22),rgba(255,255,255,.045))}.service-item.is-active:before{background:linear-gradient(180deg,rgba(31,25,58,.96),rgba(15,14,26,.98))}.service-item>span{position:relative;z-index:1}.service-item:before{content:"";position:absolute;inset:7px;border-radius:21px;background:rgba(17,18,26,.94);z-index:0}.service-item b{display:block;color:#fbfaff;font-size:17px}.service-item span{color:#b9bed2;font-weight:850}.service-price{background:linear-gradient(135deg,var(--violet),var(--violet2));border-radius:999px;padding:12px 16px;color:#fff!important;text-shadow:0 1px 2px rgba(0,0,0,.24);box-shadow:inset 0 1px 1px rgba(255,255,255,.28)}.catalog-shell{display:grid;grid-template-columns:minmax(0,1.08fr) minmax(360px,.92fr);gap:34px;align-items:start}.selector-card{position:sticky;top:112px}.service-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.pay-card{display:flex;align-items:center;gap:12px;cursor:pointer}.pay-card input{width:auto;accent-color:var(--violet)}.empty{border:1px dashed rgba(255,255,255,.17);border-radius:26px;padding:32px;text-align:center;color:var(--soft);background:rgba(255,255,255,.03)}
        .auth-shell{min-height:calc(100dvh - 110px);display:grid;place-items:center;padding:84px 0}.auth-card{width:min(560px,calc(100vw - 38px))}.mini-links{display:flex;justify-content:space-between;gap:12px;margin-top:20px;color:var(--soft)}.order-head{display:flex;justify-content:space-between;gap:22px;align-items:flex-start;flex-wrap:wrap}.order-timeline{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:22px}.time-step{border-radius:22px;padding:16px;background:rgba(255,255,255,.055);border:1px solid rgba(255,255,255,.085);color:var(--soft)}.time-step.done{border-color:rgba(122,242,190,.28);color:#ddfff1;background:rgba(122,242,190,.08)}
        body.home-page{min-height:100dvh}.home-page .footer,.home-page .chat-float{display:none}.home-page main{min-height:auto}.home-hero{min-height:calc(100dvh - 112px);padding:18px 0 24px;display:flex;align-items:center}.home-carousel{width:100%;height:min(740px,calc(100dvh - 172px));min-height:520px;border-radius:42px;box-shadow:var(--ambient)}.home-slide{position:absolute;inset:0;display:grid;grid-template-columns:1fr .82fr;gap:32px;align-items:center;padding:60px;background-image:linear-gradient(90deg,rgba(5,5,9,.96),rgba(5,5,9,.76) 48%,rgba(5,5,9,.28)),var(--slide-image);background-size:cover;background-position:center}.home-slide:after{content:"";position:absolute;inset:0;background:radial-gradient(circle at 15% 19%,rgba(139,108,255,.28),transparent 36%),linear-gradient(180deg,transparent,rgba(0,0,0,.36));pointer-events:none}.home-slide-content,.home-slide-card{position:relative;z-index:1;min-width:0;max-width:100%}.home-slide h1{max-width:660px;font-size:clamp(42px,4.7vw,68px);line-height:1.04;letter-spacing:-.07em;margin:0 0 24px;overflow-wrap:anywhere;word-break:break-word}.home-slide p{font-size:clamp(17px,2vw,24px);line-height:1.72;color:#d9dced;max-width:780px;margin:0 0 32px}.hero-actions{display:flex;gap:14px;flex-wrap:wrap;margin-bottom:28px}.home-slide-card{border-radius:34px;padding:32px;background:linear-gradient(180deg,rgba(255,255,255,.09),rgba(255,255,255,.035));border:1px solid rgba(255,255,255,.11);box-shadow:inset 0 1px 1px rgba(255,255,255,.11)}.home-slide-card .price{font-size:clamp(48px,6vw,82px)}.home-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:13px;margin-top:24px}.home-metric{border-radius:22px;background:rgba(255,255,255,.065);border:1px solid rgba(255,255,255,.09);padding:17px}.home-metric b{font-size:24px;display:block}.home-metric span{color:#c6cadd;font-size:13px}.home-carousel .dots{bottom:26px}.home-admin-note{position:absolute;right:28px;top:26px;z-index:2;color:#d7d8e8;font-weight:850;background:rgba(255,255,255,.075);border:1px solid rgba(255,255,255,.11);border-radius:999px;padding:9px 13px}
        .reveal-ready{opacity:0;transform:translateY(42px);filter:blur(10px);transition:opacity .9s var(--spring),transform .9s var(--spring),filter .9s var(--spring)}.reveal-ready.is-visible{opacity:1;transform:translateY(0);filter:blur(0)}
        @media(max-width:1020px){.nav,.userbar{display:none}.menu-btn{display:grid}.topbar{top:12px;margin-top:12px}.topbar-inner{min-height:70px}.catalog-shell,.home-slide{grid-template-columns:1fr}.selector-card{position:static}.grid4,.grid5{grid-template-columns:repeat(2,minmax(0,1fr))}.section{padding:86px 0}.section-tight{padding:58px 0}.home-page main{min-height:auto}.home-hero{min-height:calc(100dvh - 96px);padding:16px 0 22px}.home-carousel{height:auto;min-height:660px}.home-slide{align-content:start;padding:42px 28px}.home-metrics{grid-template-columns:1fr}.home-admin-note{display:none}}
        @media(max-width:768px){.container{width:min(100vw - 28px,var(--max))}.brand-name{font-size:20px}.brand-domain{display:none}.brand-mark{width:44px;height:44px}.grid,.grid3,.grid4,.grid5,.service-grid,.order-timeline{grid-template-columns:1fr}.catalog-shell{display:block}.panel{padding:22px;border-radius:26px}.panel:before{border-radius:20px}.section-title{font-size:34px;line-height:1.08;text-align:left;letter-spacing:-.052em}.section-sub{text-align:left;margin-bottom:30px}.hero-actions .btn{width:100%}.copy-row{grid-template-columns:1fr}.copy-row .btn{width:100%}.chat-float{right:16px;bottom:16px;width:52px;height:52px}.service-item{grid-template-columns:auto 1fr}.service-price{grid-column:1 / -1;text-align:center}.table{min-width:700px}.home-carousel{min-height:640px;border-radius:30px}.home-slide{padding:30px 20px}.home-slide h1{font-size:36px;line-height:1.07;max-width:100%}.home-slide p{font-size:15px;max-width:100%}.home-slide-card{padding:24px;border-radius:26px}.mobile-menu a,.mobile-menu button{font-size:21px}}
        @media(max-width:430px){.topbar{width:calc(100vw - 20px)}.topbar-inner{gap:8px;padding:9px}.brand{min-width:0}.brand-name{font-size:18px;white-space:nowrap}.menu-btn{flex:0 0 52px;width:52px;height:52px}.section-tight{padding:42px 0}.home-slide h1{font-size:34px}.home-carousel{min-height:640px}.hero-actions,.home-metrics{width:100%}}
    </style>
</head>
<body class="@yield('body_class')">
<header class="topbar">
    <div class="topbar-inner">
        <a class="brand" href="{{ route('home') }}" aria-label="{{ __('sms.brand') }}">
            <span class="brand-mark"><span>✦</span></span>
            <span class="brand-name">ZXAIHUB <em>SMS</em><span class="brand-domain">{{ __('sms.domain') }}</span></span>
        </a>
        <nav class="nav" aria-label="{{ __('sms.common.main_nav') }}">
            <a href="{{ route('sms.index') }}" class="{{ request()->routeIs('sms.index') ? 'active' : '' }}">{{ __('sms.nav.get_number') }}</a>
            <a href="{{ route('sms.account.numbers') }}" class="{{ request()->routeIs('sms.account.numbers') ? 'active' : '' }}">{{ __('sms.nav.my_numbers') }}</a>
            <a href="{{ route('sms.recharge.index') }}" class="{{ request()->routeIs('sms.recharge.*') ? 'active' : '' }}">{{ __('sms.nav.recharge') }}</a>
            <a href="{{ route('sms.query') }}" class="{{ request()->routeIs('sms.query') ? 'active' : '' }}">{{ __('sms.nav.query') }}</a>
        </nav>
        <div class="userbar">
            <form class="lang-switch" method="get" action="{{ url()->current() }}">
                @foreach(request()->except('lang') as $key => $value)
                    @if(is_scalar($value))<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endif
                @endforeach
                <select name="lang" aria-label="{{ __('sms.common.language') }}" onchange="this.form.submit()">
                    @foreach(config('sms.locale.supported') as $code => $label)
                        <option value="{{ $code }}" @if(app()->getLocale()===$code) selected @endif>{{ $label }}</option>
                    @endforeach
                </select>
            </form>
            @auth
                @php($navWallet = app(\App\Services\Sms\SmsWalletService::class)->wallet(auth()->user()))
                <span class="avatar">{{ mb_substr(auth()->user()->name ?: auth()->user()->email, 0, 1) }}</span>
                <span class="user-meta">{{ auth()->user()->name ?: __('sms.common.user') }}<small>{{ __('sms.common.balance') }} ¥{{ number_format((float)$navWallet->balance, 2) }}</small></span>
                <a class="btn btn-primary" href="{{ route('sms.recharge.index') }}">{{ __('sms.nav.recharge') }}</a>
                <form method="post" action="{{ route('logout') }}">@csrf<button class="btn btn-dark" type="submit">{{ __('sms.nav.logout') }}</button></form>
            @else
                <a class="btn btn-ghost" href="{{ route('login') }}">{{ __('sms.nav.login') }}</a>
                <a class="btn btn-primary" href="{{ route('register') }}">{{ __('sms.nav.register') }}</a>
            @endauth
        </div>
        <button class="menu-btn" type="button" data-menu-toggle aria-label="Menu"><span></span><span></span><span></span></button>
    </div>
    <div class="container mobile-menu" data-mobile-menu>
        <div class="mobile-langs">
            @foreach(config('sms.locale.supported') as $code => $label)
                <a href="{{ request()->fullUrlWithQuery(['lang'=>$code]) }}">{{ $label }}</a>
            @endforeach
        </div>
        <a href="{{ route('sms.index') }}">{{ __('sms.nav.get_number') }}</a>
        <a href="{{ route('sms.account.numbers') }}">{{ __('sms.nav.my_numbers') }}</a>
        <a href="{{ route('sms.recharge.index') }}">{{ __('sms.nav.recharge') }}</a>
        <a href="{{ route('sms.query') }}">{{ __('sms.nav.query') }}</a>
        @auth
            <form method="post" action="{{ route('logout') }}">@csrf<button type="submit">{{ __('sms.nav.logout') }}：{{ auth()->user()->email }}</button></form>
        @else
            <a href="{{ route('login') }}">{{ __('sms.nav.email_login') }}</a>
            <a href="{{ route('register') }}">{{ __('sms.nav.register') }}</a>
        @endauth
    </div>
</header>

@if(session('ok'))<div class="ok">{{ session('ok') }}</div>@endif
@if(session('quote_changed'))<div class="err">{{ session('quote_changed') }} · {{ __('sms.common.new_price') }}：¥{{ session('new_price') }}</div>@endif
@if($errors->any())<div class="err">{{ $errors->first() }}</div>@endif

<main>
    @yield('content')
</main>

<a class="chat-float" href="{{ route('sms.query') }}" title="{{ __('sms.nav.query') }}">☏</a>
<footer class="footer">
    <div class="container footer-inner">
        <div><b>ZXAIHUB SMS</b><br><span>{{ __('sms.domain') }} · {{ __('sms.footer.desc') }}</span></div>
        <div><a href="{{ route('sms.index') }}">{{ __('sms.nav.get_number') }}</a><a href="{{ route('sms.query') }}">{{ __('sms.nav.query') }}</a><a href="/sms-admin">{{ __('sms.nav.admin') }}</a></div>
    </div>
</footer>
<script>
(function(){
    var btn=document.querySelector('[data-menu-toggle]');
    var menu=document.querySelector('[data-mobile-menu]');
    if(btn&&menu){btn.addEventListener('click',function(){btn.classList.toggle('is-open');menu.classList.toggle('open');document.body.classList.toggle('menu-open');});}
    var targets=[].slice.call(document.querySelectorAll('.panel,.feature-card,.step-card,.faq-card,.service-item,.pay-card,.stat'));
    if('IntersectionObserver' in window){
        var io=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('is-visible');io.unobserve(entry.target);}});},{threshold:.12,rootMargin:'0px 0px -8% 0px'});
        targets.forEach(function(el,idx){el.classList.add('reveal-ready');el.style.transitionDelay=Math.min(idx%6*70,350)+'ms';io.observe(el);});
        setTimeout(function(){targets.forEach(function(el){el.classList.add('is-visible');});}, 120);
    }else{targets.forEach(function(el){el.classList.add('is-visible');});}
})();
</script>
@yield('scripts')
</body>
</html>
